baseURL = 'https://smittyweygant.com/'
languageCode = 'en-us'
title = 'Smitty Weygant'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
featured_image = '/images/smitty-jackson-center-mothership.jpeg'

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
  expiryDate = ['expirydate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
  publishDate = ['publishdate', 'pubdate', 'published', 'date']

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 8 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
# contentDir = "content/en"
# languageCode = 'en-US'
# weight = 1
# title = "Ananke"

[sitemap]
# changefreq = "monthly"
# priority = 0.5
# filename = "sitemap.xml"

[params]
text_color = ""
author = "Smitty Weygant"
favicon = ""
site_logo = ""
show_reading_time = true
description = "Smitty Weygant's web site and blog"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 5

[params.ananke.social.share]
networks = [
  "email",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin",
  "facebook"
]

[[params.ananke.social.github]]
username = "smittyweygant"

[params.ananke.social.facebook]
username = "smittoid"
# profilelink = "https://www.facebook.com/smittoid"

[params.ananke.social.linkedin]
username = "smithweygant"


